### ISSUE TITLE
using the software name 'xVASynth' in config ini  breaks main.py

### ISSUE THREAD

**Issue by jonathonbarton** [Pathos14489/Pantella#2]
Steps to reproduce:

change tts_engine to = xVASynth and not xvasynth

main.py complains: "Could not find inference engine: xVASynth! Please check your config.ini file and try again!"

**Comment by Pathos14489** [comment]
Fixed.
https://github.com/Pathos14489/Mantella/commit/4226e03b7887f0b6a16a2b014c97d05416b46b8b
